In [ ]:
# venv setup for fraud detection project
# ----------------------------------------
# python -m venv fraud_detection
# fraud_detection\Scripts\activate

# Install ipykernel to use the virtual environment in Jupyter Notebook as Kernel
# -------------------------------------------------------------------------------
# pip install ipykernel
# Register your venv as a kernel
# python -m ipykernel install --user --name=fraud_detection --display-name "Python (fraud_detection)"

In [ ]:
# In Python, a single backslash \ is an escape character, so for example:
# "C:\Users\49152\anaconda3\Scripts\180\DAYS_COMMITED\20260122\ML_Proj"


# …Python interprets \U as the start of a Unicode escape, which will raise an error.

# ✅ How to fix it

# You have three options:

# 1. Use raw string (simplest)
# path = kagglehub.dataset_download(
#     "amanalisiddiqui/fraud-detection-dataset",
#     path=r"C:\Users\49152\anaconda3\Scripts\180\DAYS_COMMITED\20260122\ML_Proj"
# )


# The r before the string tells Python: “don’t interpret backslashes as escapes.”

# 2. Use forward slashes

# Windows supports / in paths:

# path = kagglehub.dataset_download(
#     "amanalisiddiqui/fraud-detection-dataset",
#     path="C:/Users/49152/anaconda3/Scripts/180/DAYS_COMMITED/20260122/ML_Proj"
# )

# 3. Escape backslashes
# path = kagglehub.dataset_download(
#     "amanalisiddiqui/fraud-detection-dataset",
#     path="C:\\Users\\49152\\anaconda3\\Scripts\\180\\DAYS_COMMITED\\20260122\\ML_Proj"
# )


# Every backslash is doubled so Python reads it literally.

In [7]:
import os
import kagglehub

path = kagglehub.dataset_download("amanalisiddiqui/fraud-detection-dataset")

print("Dataset downloaded to:", path)
print("Files in dataset folder:", os.listdir(path))

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (0.4.1).
Dataset downloaded to: C:\Users\49152\.cache\kagglehub\datasets\amanalisiddiqui\fraud-detection-dataset\versions\1
Files in dataset folder: ['AIML Dataset.csv']

In [9]:
import pandas as pd
import os

dataset_file = os.path.join(
    r"C:\Users\49152\.cache\kagglehub\datasets\amanalisiddiqui\fraud-detection-dataset\versions\1",
    "AIML Dataset.csv"
)

df = pd.read_csv(dataset_file)
print(df.head())

   step      type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1   PAYMENT   9839.64  C1231006815       170136.0       160296.36
1     1   PAYMENT   1864.28  C1666544295        21249.0        19384.72
2     1  TRANSFER    181.00  C1305486145          181.0            0.00
3     1  CASH_OUT    181.00   C840083671          181.0            0.00
4     1   PAYMENT  11668.14  C2048537720        41554.0        29885.86

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud
0  M1979787155             0.0             0.0        0               0
1  M2044282225             0.0             0.0        0               0
2   C553264065             0.0             0.0        1               0
3    C38997010         21182.0             0.0        1               0
4  M1230701703             0.0             0.0        0               0

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns # pip install --upgrade matplotlib seaborn

In [2]:
import warnings
warnings.filterwarnings("ignore")
sns.set(style="whitegrid")

In [4]:
df = pd.read_csv("AIML Dataset.csv")

In [5]:
df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype
---  ------          -----
 0   step            int64
 1   type            object
 2   amount          float64
 3   nameOrig        object
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        object
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64
 10  isFlaggedFraud  int64
dtypes: float64(5), int64(3), object(3)
memory usage: 534.0+ MB

In [8]:
df.columns

Index(['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig',
       'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFraud',
       'isFlaggedFraud'],
      dtype='object')

In [9]:
df["isFraud"].value_counts()

isFraud
0    6354407
1       8213
Name: count, dtype: int64

In [10]:
df["isFlaggedFraud"].value_counts()

isFlaggedFraud
0    6362604
1         16
Name: count, dtype: int64

In [ ]:
df.isnull() # if there is any na values # cellwise True/False

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
6362615,False,False,False,False,False,False,False,False,False,False,False
6362616,False,False,False,False,False,False,False,False,False,False,False
6362617,False,False,False,False,False,False,False,False,False,False,False
6362618,False,False,False,False,False,False,False,False,False,False,False
6362619,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum() # columnwise sum of na values

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [ ]:
df.isnull().sum().sum() # total na values in the dataframe

0

In [14]:
df.shape

(6362620, 11)

In [19]:
df["isFraud"].value_counts() # number of fraud and non-fraud cases in the dataset
df["isFraud"].value_counts()[1] # number of fraud cases in the dataset
df["isFraud"].value_counts()[1] / df.shape[0] # proportion of fraud cases in the dataset
df["isFraud"].value_counts()[1] / df.shape[0] * 100  # percentage of fraud cases in the dataset
round( df["isFraud"].value_counts()[1] / df.shape[0] * 100 , 2)  # rounded percentage of fraud cases in the dataset

isFraud
0    6354407
1       8213
Name: count, dtype: int64

8213

0.001290820448180152

0.12908204481801522

0.13

In [ ]:
df["type"].value_counts().plot(kind='bar'),title = "Transaction Type Distribution", color =